### ISSUE TITLE
Can not use workflow 

### ISSUE THREAD

**Issue by samhvw8** [jdno/alfred-gitignore#4]
Hi @jdno , 
I download workflow from release and Packal 
when first run 'gitignore' i can only get 'Build a .gitignore file from templates'
i try some input but all get then same error 

[23:36:28.834] ERROR: gitignore[Script Filter] Code 1: {"items":[{"subtitle":"Path to repository does not exist","title":"Error running gitignore workflow"}]}

**Comment by jdno** [comment]
Hi @samhvw8,

sorry to hear that! I fixed the issue in [version 2.0.1](https://github.com/jdno/alfred-gitignore/releases/tag/v2.0.1), which you can download from GitHub now and a bit later from Packal. Should the issues persist for you, let me know please.

The cause of the issue was that while Alfred provides a path to their data directories to workflows, it does not create this directory for them. `alfred-gitignore` assumed that the directory would exist, and failed with the posted error if it doesn't. The new version doesn't expect the directory to exist, and instead creates it if it is missing.

Another lesson learned here is to reset the data directory when testing the workflow during development. :+1:

**Comment by samhvw8** [comment]
Thank for your work  🎉
